# Generated by Django 5.0.2 on 2024-02-18 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_descriptuon_event_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['meeting_time'], name='meeting_time_index'),
        ),
    ]
