# Generated by Django 5.0.2 on 2024-02-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_meeting_time_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
