# Generated by Django 5.0.2 on 2024-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='meeting_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
