# Generated by Django 5.0.1 on 2024-01-21 16:00

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=notes.models.upload_to),
        ),
    ]
