# Generated by Django 5.0 on 2024-01-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_tag_alter_note_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', to='notes.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='content',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
